### ISSUE TITLE
No auto remove trees?

### ISSUE THREAD

**Issue by MarcHagen** [betterphp/NoFloatingTrees#2]
I have logblock installed, but after some time the floating tree that I created wasn't gone.
Yes i was 50 blocks away, yes i waited kinda very long.

Can you help?

**Comment by betterphp** [comment]
Try the /nftpurge command. If it does not vanish then it means it was not detected for some reason.

**Comment by MarcHagen** [comment]
Yes that works, but the trees doesn't vanish at it own.

**Comment by betterphp** [comment]
Someone must have been too close. Only possible cause.

**Comment by MarcHagen** [comment]
Well i have a test world.
I places a tree, (Sapling & BoneMeal) i remove the bottom blocks.
Checked with logblock if its logged. (Yes)
Going stand 75 blocks away and watch the tree.
After a hour it wasn't gone. And no one can enter that world.

**Comment by betterphp** [comment]
Hmm. I don't have an answer for that then. The distance check will be replaced with a time delay soon anyway so that should fix it.
