### ISSUE TITLE
Multiworld Support

### ISSUE THREAD

**Issue by Nomy** [betterphp/NoFloatingTrees#3]
Is it possible to add multiworld support so this plugin would not affect certain world?

I think it will be nice if we could set what worlds we want NoFloatingTrees to be active :)

**Comment by betterphp** [comment]
I don't see why not :) consider it on my todo list :D

**Comment by betterphp** [comment]
Done :D

**Comment by Nomy** [comment]
Thanks alot!!!

Where can I access the new build?

**Comment by betterphp** [comment]
I just uploaded it to BukkitDev but it's still waiting on approval, you can use this direct link if you are that desperate http://dev.bukkit.org/media/files/596/168/NoFloatingTrees.jar

It's pretty straight forward, there is a new ignore-worlds config option :)

**Comment by Nomy** [comment]
I don't want to wait 4-5 hours for bukkit team to approve :P

Thanks alot! :)

**Comment by betterphp** [comment]
More like 14 recently, very frustrating when a fix only took 10 minutes !

No problem anyway :)
